### ISSUE TITLE
Specifying Entity Picture does not disable Icon

### ISSUE THREAD

**Issue by wazoo** [balloob/home-assistant-polymer#19]
When specifying an entity_picture for something it just layers it on-top of the icon and I would expect that entity_picture would disable the icon.

Examples:
![image](https://cloud.githubusercontent.com/assets/216878/12312599/fca755f6-ba1d-11e5-9ce3-0bfa149ef6e6.png)

![image](https://cloud.githubusercontent.com/assets/216878/12312661/5886d040-ba1e-11e5-9849-33e18e2e4223.png)

You can see here that the regular bulb icon is behind the image that I have specified. It seems specifying icon: false or icon: ' ' in the customize file gets rid of it because its then not a valid icon name but that seems pretty hack-y.  

Not sure what the vision is but I will put together a pull request where the picture disables the icon if that is the direction that you want to go.

**Comment by balloob** [comment]
I did it on purpose because you will be able to see what kind of device it is while the picture is loading/fails to load. A nice solution would be to make it in such a way that the icon will be hidden when a picture has loaded successfully.

**Comment by wazoo** [comment]
Yeah, I was thinking about that after I posted this.  I was thinking about it more and I thought of a super simple fix, ill put together a quick pull request for it.

**Comment by wazoo** [comment]
So I accidentally opened the PR up on my own fork, no idea how or why, oh well.

**Comment by balloob** [comment]
GitHub can be a bit confusing sometimes. You'll get the hang of it, no worries :+1:

**Comment by wazoo** [comment]
You bet, probably needed more coffee!  Glad to help, wanting to learn polymer anyway so there might be more additions coming :D
