### ISSUE TITLE
Why use require and not import

### ISSUE THREAD

**Issue by mbinette** [balloob/home-assistant-polymer#31]
What is the reason you use both `import` and `require` in the js files? For example, in home-assistant-main.js you use `import` to bring in Polymer, nuclearObserver, and a few others but use `require` to bring in things like partial-cards and partial-logbook.

**Comment by balloob** [comment]
It is to differentiate which imports are due to having to import the javascript for webcomponents vs JS modules. In the end it is handled all the same.
